permissions:
  id-token: write
  contents: read

name: 'Deploy review environment'
on:
  pull_request:

env:
  PULUMI_STACK: "${{ vars.PULUMI_ORG }}/pulumi_ga_review_apps/pr${{ github.event.pull_request.number }}"

jobs:
  build-review-base:
    runs-on: ubuntu-latest
    env:
      PULUMI_DIR: "src/base"
    outputs:
      review_client_id: ${{ steps.base_outputs.outputs.review_client_id }}
      review_principal_id: ${{ steps.base_outputs.outputs.review_principal_id }}
      review_rg_name: ${{ steps.base_outputs.outputs.review_rg_name }}
    steps:
    - uses: actions/checkout@v4
    - uses: pulumi/auth-actions@v1
      with:
        organization: ${{ vars.pulumi_org }}
        scope: ${{ vars.pulumi_scope }}
        requested-token-type: urn:pulumi:token-type:access_token:personal
    - uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 8.0.x
    - uses: pulumi/actions@v6
      name: Install pulumi
    - run: pulumi stack select -C "${{ env.PULUMI_DIR }}" -c -Q "${{ env.PULUMI_STACK }}"
    - uses: pulumi/actions@v6
      with:
        command: up
        stack-name: "${{ env.PULUMI_STACK }}"
        work-dir: "${{ env.PULUMI_DIR }}"
        config-map: "{ \"pulumi_ga_review_apps:pr_number\": { value: \"${{ github.event.pull_request.number }}\", secret: false } }"
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ vars.clientId }}
        ARM_TENANT_ID: ${{ vars.tenantId }}
    - name: Save stack outputs
      id: review_outputs
      run: |
        echo "review_client_id=$(pulumi stack output 'mi-review-app:clientId')" >> "$GITHUB_OUTPUT"
        echo "review_principal_id=$(pulumi stack output 'mi-review-app:principalId')" >> "$GITHUB_OUTPUT"
        echo "review_rg_name=$(pulumi stack output 'rg-review-app:name')" >> "$GITHUB_OUTPUT"
  build-review:
    runs-on: ubuntu-latest
    needs: build-review-base
    steps:
    - uses: actions/checkout@v4
    - uses: pulumi/auth-actions@v1
      with:
        organization: ${{ vars.pulumi_org }}
        scope: ${{ vars.pulumi_scope }}
        requested-token-type: urn:pulumi:token-type:access_token:personal
    - uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 8.0.x
    - uses: pulumi/actions@v6
      with:
        command: up
        stack-name: "review_pr${{ github.event.pull_request.number }}"
        work-dir: src/review_app
        config-map: "{ \"review_app:stackName\": { value: \"${{ env.PULUMI_STACK }}\", secret: false } }"
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ needs.build-review-base.outputs.review_client_id }}
        ARM_TENANT_ID: ${{ vars.tenantId }}
