permissions:
  id-token: write
  contents: read

name: 'Hello world'
on:
  pull_request:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pulumi/auth-actions@v1
      with:
        organization: ${{ vars.pulumi_org }}
        scope: ${{ vars.pulumi_scope }}
        requested-token-type: urn:pulumi:token-type:access_token:personal
    - uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: |
          8.0.x
          9.0.x
    - uses: pulumi/actions@v6
      with:
        command: up
        stack-name: base
        work-dir: src/base
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ vars.clientId }}
        ARM_TENANT_ID: ${{ vars.tenantId }}